name: Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Build debug
        run: ./gradlew build
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: |
            ./app/build/outputs/apk/debug/app.apk
            ./app/build/outputs/apk/debug/output-metadata.json
